export const queryKeys = {
  auth: ['auth', 'me'] as const,
  notifications: ['me', 'notifications'] as const,
  campaigns: ['campaigns'] as const,
  campaign: (campaignId: string) => ['campaigns', campaignId] as const,
  campaignMembers: (campaignId: string) => ['campaigns', campaignId, 'members'] as const,
  campaignMap: (campaignId: string) => ['campaigns', campaignId, 'map'] as const,
  campaignPhase: (campaignId: string) => ['campaigns', campaignId, 'phase'] as const,
  campaignPlatoons: (campaignId: string) => ['campaigns', campaignId, 'platoons'] as const,
  campaignPlatoon: (campaignId: string, platoonId: string) => ['campaigns', campaignId, 'platoons', platoonId] as const,
  myOrders: (campaignId: string, turnNumber: number) => ['campaigns', campaignId, 'turns', turnNumber, 'orders', 'me'] as const,
  resolutionSummary: (campaignId: string, turnNumber: number) => ['campaigns', campaignId, 'turns', turnNumber, 'resolution'] as const,
  battleDetail: (campaignId: string, battleId: string) => ['campaigns', campaignId, 'battles', battleId] as const,
  auditLog: (campaignId: string) => ['campaigns', campaignId, 'audit'] as const,
  playerTerritory: (campaignId: string, territoryId: string) => ['campaigns', campaignId, 'territories', territoryId] as const,
  gmTerritory: (campaignId: string, territoryId: string) => ['campaigns', campaignId, 'territories', territoryId, 'gm'] as const,
  invite: (token: string) => ['invites', token] as const,
}
